# permissions for end users to view scalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaler-viewer-role
rules:
- apiGroups:
  - api.scaler.com
  resources:
  - scalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.scaler.com
  resources:
  - scalers/status
  verbs:
  - get
